### PR TITLE
code update

### LINKED ISSUE #138: [BE] The content blog posts index API endpoint is not returning any blog posts
### Bug Description

The endpoint `GET https://staging-api.learnhub.mk/content/blog-posts` is not returning any blog posts.

Please investigate why this is a problem.

The blog posts on the website work fine: `GET https://staging-api.learnhub.mk/blog-posts`

### LINKED ISSUE #139: [BE] The update content blog posts API endpoint throws an error
### Bug description

The API endpoint for updating the blog posts in the content module throws an error. 

Please investigate and fix the problem.

Image

### LINKED ISSUE #140: [BE] The content blog post show API endpoint is not returning any blog post details
### Bug description

When you try to do a `GET https://staging-api.learnhub.mk/content/blog-posts/50`, all of the data is returned but with null values.

Please investigate and fix the problem.

### PR DESCRIPTION
**Pull request by KalimeroMK**

### CODE REVIEW

File: app/Content/src/Http/Controllers/BlogPostController.php [hunk 1]
```diff
@@ -81,8 +79,9 @@ public function store(CreateBlogPostRequest $request): BlogPostsResource
     #[Authenticated]
     #[Endpoint(title: 'Blog post', description: 'This endpoint returns a single blog post')]
     #[Group('Content')]
-    public function show(BlogPost $blogPost, BlogPostPermissionsRequest $request): BlogPostsResource
+    public function show(int $blogPost, BlogPostPermissionsRequest $request): BlogPostsResource
     {
+        $blogPost = BlogPost::findOrFail($blogPost);
```
Comment (davorminchorov) [inline app/Content/src/Http/Controllers/BlogPostController.php]: use with() and remove the load() method below.

**Review by davorminchorov — APPROVED** [review]
