### PR TITLE
fix wrong example doc for api

### LINKED ISSUE #140: [BE] The content blog post show API endpoint is not returning any blog post details
### Bug description

When you try to do a `GET https://staging-api.learnhub.mk/content/blog-posts/50`, all of the data is returned but with null values.

Please investigate and fix the problem.

### PR DESCRIPTION
**Pull request by KalimeroMK**
Remove Constructor Injection: The constructor injection is removed since FormRequest instances are not resolved through the container in a way that supports constructor injection
Use app() Helper: The app() helper function is used within the rules method to resolve the MailboxValidEmail rule from the container

### CODE REVIEW

File: app/Content/routes/content-routes.php [hunk 1]
```diff
@@ -5,13 +5,13 @@
...
-Route::group(['prefix' => '/content', 'middleware' => ['auth:api', 'treblle', 'role:content_manager']], function () {
+Route::group(['prefix' => '/content', 'middleware' => ['auth:api', 'treblle']], function () {
     Route::resource('/blog-posts', BlogPostController::class)->except('create', 'edit');
     Route::resource('/blog-post-tags', BlogPostTagsController::class)->only('index', 'store', 'update', 'destroy')
         ->name('index', 'content.blog-post-tags.index')
         ->name('show', 'content.blog-post-tags.show')
         ->name('store', 'content.blog-post-tags.store')
         ->name('update', 'content.blog-post-tags.update')
-        ->name('destroy', 'content.blog-post-tags.destroy');
+        ->name('destroy', 'content.blog-pos t-tags.destroy');
```
Comment (davorminchorov) [inline app/Content/routes/content-routes.php]: Typo

**Review by davorminchorov — APPROVED** [review]
